[package]
name = "crates-index"
description = "Library for retrieving and interacting with the crates.io index"
version = "0.1.2"
authors = ["Corey Farwell <coreyf@rwell.org>"]
keywords = ["packaging", "index", "dependencies", "crate", "meta"]
repository = "https://github.com/frewsxcv/rust-crates-index"
license = "Apache-2.0"

[dependencies]
git2 = "0.2.11"
glob = "0.2.10"
rustc-serialize = "0.3.14"
